version: "3"
services:
  almanack:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:11.1
    ports:
      - "5643:5432"
